# Generated by Django 3.0.7 on 2020-07-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20200729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationchart',
            name='img',
            field=models.ImageField(blank=True, height_field=1080, null=True, upload_to='rotation_chart/%Y/%m/%d/', verbose_name='轮播图图片', width_field=1920),
        ),
    ]
