# Generated by Django 3.0.7 on 2020-07-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20200731_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationchart',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rotation_chart/%Y/%m/%d/', verbose_name='轮播图图片'),
        ),
    ]
