# Generated by Django 3.0.7 on 2020-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20200731_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationchart',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='轮播图标题'),
        ),
    ]
